variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    MYSQL_ROOT_PASSWORD: app
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/development/public
    DEVELOPMENT_BRANCH: "master"
    PLATFORM_BRANCH: "master"
    RUN_IN_MR: 'true'

stages:
    - Static analysis
    - Testing

default:
    image: shopware/development:latest
    before_script:
        - zip -rq plugin.zip .
        - git clone --branch $DEVELOPMENT_BRANCH http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/development.git
        - rm -rf development/platform
        - git clone --branch $PLATFORM_BRANCH http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git development/platform
        - unzip -q plugin.zip -d development/custom/plugins/SwagOrderMailDistributor
        - cd development
        - cp -v dev-ops/gitlab/.psh.yaml.override .
        - /entrypoint supervisord > /dev/null 2>&1 &

# Stage: Static analyzes
Static analyze:
    stage: Static analysis
    services:
        -   name: mysql:5.7
            alias: mysql
    script:
        - echo matrix config
        - echo DEVELOPMENT_BRANCH $DEVELOPMENT_BRANCH
        - echo PLATFORM_BRANCH $PLATFORM_BRANCH
        - ./psh.phar init
        - php bin/console plugin:install --activate SwagOrderMailDistributor
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagOrderMailDistributor
        - bin/static-analyze.sh
        - cd $CI_PROJECT_DIR/development
        - php dev-ops/analyze/vendor/bin/php-cs-fixer fix --config=vendor/shopware/platform/.php_cs.dist --dry-run -vvv --allow-risky=yes --format=junit custom/plugins/SwagOrderMailDistributor | tee php-cs-fixer.xml
        - ./psh.phar administration:init --APP_ENV="dev"
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagOrderMailDistributor
        - ./../../../vendor/shopware/platform/src/Administration/Resources/app/administration/node_modules/.bin/eslint --ignore-path .eslintignore --config ../../../vendor/shopware/platform/src/Administration/Resources/app/administration/.eslintrc.js --ext .js,.vue .
    rules:
        -   if: '$CI_COMMIT_BRANCH == "master"'
        -   if: '$RUN_IN_MR == "true" && $CI_PIPELINE_SOURCE == "merge_request_event"'
    parallel:
        matrix:
            -   PLATFORM_BRANCH: '6.3.0.0'
                DEVELOPMENT_BRANCH: 'master'
            -   PLATFORM_BRANCH: '6.3.0.2'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.1.1'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.2.0'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: 'master'
                DEVELOPMENT_BRANCH: 'master'

ToDos resolved:
    only:
        refs:
            - merge_requests
            - master
    stage: Static analysis
    allow_failure: true
    script:
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagOrderMailDistributor
        - bin/check-todos.sh $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME

PHPUnit Coverage (6.3.x.x dev):
    only:
        refs:
            - merge_requests
            - master
    stage: Testing
    services:
        -   name: mariadb:10.3
            alias: mysql
    script:
        - ./psh.phar init
        - php bin/console plugin:install --activate SwagOrderMailDistributor
        - composer dump-autoload -d custom/plugins/SwagOrderMailDistributor
        - ./psh.phar init-test-databases
        - php -d pcov.enabled=1 -d pcov.directory=$CI_PROJECT_DIR
            vendor/bin/phpunit
            --configuration custom/plugins/SwagOrderMailDistributor/phpunit.xml.dist
            --log-junit build/artifacts/phpunit.junit.xml
            --colors=never
            --coverage-clover build/artifacts/phpunit.clover.xml
            --coverage-html build/artifacts/phpunit-coverage-html

    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    artifacts:
        paths:
            - development/build/artifacts/phpunit.clover.xml
        reports:
            junit: development/build/artifacts/phpunit.junit.xml

PHPUnit:
    stage: Testing
    services:
        -   name: mysql:5.7
            alias: mysql
    script:
        - echo matrix config
        - echo DEVELOPMENT_BRANCH $DEVELOPMENT_BRANCH
        - echo PLATFORM_BRANCH $PLATFORM_BRANCH
        - ./psh.phar init
        - php bin/console plugin:install --activate SwagOrderMailDistributor
        - ./psh.phar init-test-databases
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagOrderMailDistributor
        - bin/phpunit.sh
    rules:
        -   if: '$CI_COMMIT_BRANCH == "master"'
        -   if: '$RUN_IN_MR == "true" && $CI_PIPELINE_SOURCE == "merge_request_event"'
    parallel:
        matrix:
            -   PLATFORM_BRANCH: '6.2'
                DEVELOPMENT_BRANCH: '6.2'
            -   PLATFORM_BRANCH: '6.3.0.0'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.0.2'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.1.1'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.2.0'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: 'master'
                DEVELOPMENT_BRANCH: 'master'
